// Satellite colours for the Docklands 3D terrain: one RGB value per terrain vertex, from the least cloudy recent
// Sentinel-2 L2A true-colour image (10 m) over Canary Wharf, found through the Earth Search STAC API.
//
//   NODE_USE_ENV_PROXY=1 node magpie/cwplans/tools/build-imagery.mjs [from-date]    # default: the last 120 days
//
// in:  docklands/data/area.js (terrain grid), https://earth-search.aws.element84.com/v1 (STAC), the TCI COG on S3
//      (read with HTTP range requests: only the window over the model box is fetched)
// out: docklands/data/imagery.js  globalThis.DOCKLANDS_IMAGERY = { scene, date, cloud, attribution, nx, nz, rgb (base64) }
// Licence: Copernicus Sentinel data, free and open (attribution "Contains modified Copernicus Sentinel data").
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import proj4 from 'proj4';
import { fromUrl } from 'geotiff';
import { TOOLS, UA } from './lib.mjs';
import { ORIGIN } from './fetch-docklands.mjs';

const CW = join(TOOLS, '..');
globalThis.window = globalThis;
new Function(readFileSync(join(CW, 'docklands/data/area.js'), 'utf8'))();
const T = globalThis.DOCKLANDS_AREA.terrain;

const from = process.argv[2] || new Date(Date.now() - 120 * 864e5).toISOString().slice(0, 10);
const search = await fetch('https://earth-search.aws.element84.com/v1/search', { method: 'POST', headers: { 'Content-Type': 'application/json', 'User-Agent': UA }, body: JSON.stringify({
  collections: ['sentinel-2-l2a'], intersects: { type: 'Point', coordinates: [-0.0195, 51.5049] }, datetime: `${from}T00:00:00Z/${new Date().toISOString()}`,
  query: { 'eo:cloud_cover': { lt: 10 } }, sortby: [{ field: 'properties.eo:cloud_cover', direction: 'asc' }], limit: 1 }) }).then(r => r.json());
const scene = search.features?.[0]; if (!scene) throw new Error('no scene under 10% cloud since ' + from);
const href = scene.assets.visual.href, epsg = scene.properties['proj:epsg'] || 32630;
console.log(`scene ${scene.id}, ${scene.properties.datetime}, cloud ${scene.properties['eo:cloud_cover']}%, EPSG:${epsg}`);

// local metres -> BNG -> WGS84 -> UTM. The BNG step uses the Helmert transform (about 2 m), well inside a 10 m pixel.
proj4.defs('EPSG:27700', '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs');
proj4.defs(`EPSG:${epsg}`, `+proj=utm +zone=${epsg - 32600} +datum=WGS84 +units=m +no_defs`);
const toUtm = proj4('EPSG:27700', `EPSG:${epsg}`);
const pts = []; let u0 = Infinity, u1 = -Infinity, v0 = Infinity, v1 = -Infinity;
for (let j = 0; j < T.nz; j++) for (let i = 0; i < T.nx; i++) {
  const x = T.x0 + i * T.cell, z = T.z0 + j * T.cell, [u, v] = toUtm.forward([x + ORIGIN.E0, -z + ORIGIN.N0]);
  pts.push([u, v]); u0 = Math.min(u0, u); u1 = Math.max(u1, u); v0 = Math.min(v0, v); v1 = Math.max(v1, v);
}
const tif = await fromUrl(href), img = await tif.getImage(), [bx0, , , by1] = img.getBoundingBox(), [rx, ry] = img.getResolution();
const c0 = Math.floor((u0 - bx0) / rx) - 2, c1 = Math.ceil((u1 - bx0) / rx) + 2, r0 = Math.floor((v1 - by1) / ry) - 2, r1 = Math.ceil((v0 - by1) / ry) + 2;
const ras = await img.readRasters({ window: [c0, r0, c1, r1], interleave: true }), W = c1 - c0;
console.log(`window ${W} x ${r1 - r0} pixels`);
// average the pixels that fall inside each terrain cell (cell ${T.cell} m, pixel 10 m)
const half = Math.max(0, Math.round(T.cell / 2 / rx) - 0), rgb = new Uint8Array(pts.length * 3);
pts.forEach(([u, v], k) => {
  const cc = Math.round((u - bx0) / rx) - c0, rr = Math.round((v - by1) / ry) - r0; let s = [0, 0, 0], n = 0;
  for (let dr = -half; dr <= half; dr++) for (let dc = -half; dc <= half; dc++) { const c = cc + dc, r = rr + dr; if (c < 0 || r < 0 || c >= W || r >= r1 - r0) continue; const o = 3 * (r * W + c); s[0] += ras[o]; s[1] += ras[o + 1]; s[2] += ras[o + 2]; n++; }
  if (n) for (let b = 0; b < 3; b++) rgb[3 * k + b] = Math.round(s[b] / n);
});
const date = scene.properties.datetime.slice(0, 10);
const out = { scene: scene.id, date, cloud: scene.properties['eo:cloud_cover'], source: href, cell: T.cell, nx: T.nx, nz: T.nz,
  attribution: `Satellite colours: Sentinel-2 L2A true colour, ${date}, 10 m (contains modified Copernicus Sentinel data ${date.slice(0, 4)}; via Earth Search / Element 84)`,
  rgb: Buffer.from(rgb).toString('base64') };
writeFileSync(join(CW, 'docklands/data/imagery.js'), `// Generated by magpie/cwplans/tools/build-imagery.mjs on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.\nglobalThis.DOCKLANDS_IMAGERY = ${JSON.stringify(out)};\n`);
console.log(`imagery.js: ${T.nx} x ${T.nz} vertices, ${(out.rgb.length / 1024).toFixed(0)} kB`);
