PREFIX s: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX cwk: <https://danbri.github.io/londat/kgx/vocab#>
# Graphs, sources and licences
SELECT ?g ?title ?quads ?licence ?rights WHERE { GRAPH ?m { ?g a void:Dataset ; dct:title ?title ; void:triples ?quads ; dct:license ?licence . OPTIONAL { ?g dct:rights ?rights } } } ORDER BY DESC(?quads)
